### ISSUE TITLE
Make resources importable

### ISSUE THREAD

**Issue by bitfield** [checkly/terraform-provider-checkly#13]

**Comment by ianaya89** [comment]
Close due inactivity

**Comment by case-fastly** [comment]
@tnolet could your team reopen this issue? Being able to `terraform import` resources is really important, e.g. I'd like to import an Env Var which doesn't currently appear to be possible.

Thanks for considering!

**Comment by tnolet** [comment]
Hey @case-fastly have you checked out our exporter in the web UI? Should enable you to get the same benefit.

**Comment by case-fastly** [comment]
@tnolet Ooh I didn't realize that was there, this is 🔥 🔥 🔥 !

Fwiw, there's a common pattern in most Terraform docs, e.g. `https://registry.terraform.io/providers/heroku/heroku/latest/docs/resources/app#import`, to put an Import section at the bottom of every Resource doc page.

Perhaps you could consider mentioning Checkly's Export functionality in the Terraform docs, as an alternative?

**Comment by case-fastly** [comment]
So the issue here is that (as far as I know), `terraform import` is the only way to bring an existing resource (e.g. a Checkly check, alert channel, etc.) into Terraform's "state".

(there is also this new-ish `import {}` block functionality in Tf 1.5, see here for reference: https://www.youtube.com/watch?v=znfh_00EDZ0 -- but it's not working for me either)

Tf State ≠ the resource configuration blocks in a codebase, the State is entirely separate: https://developer.hashicorp.com/terraform/language/state/purpose

Checkly's web UI exporter shows resource configuration blocks, but that's only one piece of what is needed to bring a resource into Terraform. The other is the `import` step.

For example, I'm working on creating a PagerDuty alert channel, which can only be done via the web UI (in order to do the oauth dance, and fetch the token or auth needed for Checkly to post there) -- but I'd still like this to exist in our Terraform config as well.

Importing needs an `id` and I've tried using the ID integer at the end of the URL, e.g. `https://app.checklyhq.com/alerts/settings/channels/edit/pagerduty/{int}` but it ends up duplicating the PD alert channel. (you can look at our account's alert settings if you'd like to see this live, the dupe PD channel is currently there)

I think the Checkly provider here may need explicit `import` functionality for this to actually work. For example, see DNSimple's provider: https://registry.terraform.io/providers/dnsimple/dnsimple/latest/docs/resources/zone#import

**Comment by case-fastly** [comment]
@tnolet can you all provide us with an update on this? I still can't import our PagerDuty alert channel into Terraform, and manage it like we manage the rest of our Checkly config.

**Comment by case-fastly** [comment]
We found a way around it, fortunately. You all can update your Terraform docs to recommend the `import {}` block: https://developer.hashicorp.com/terraform/language/import

I used the values from the Checkly webapp's URLs for the `id = ` value, and it worked.
