### ISSUE TITLE
locations in checkly_check is required. But on UI, checks part of a group doesn't allow to change location.

### ISSUE THREAD

**Issue by pshanoop** [checkly/terraform-provider-checkly#98]
**Describe the bug**
[locations](https://registry.terraform.io/providers/checkly/checkly/latest/docs/resources/check#locations) is required in `checkly_check`. 
But checks part of a group does not require it, UI doesn't allow it to change. 
Also, due to (I guess), change of `locations` is always detected. 

This behavior is conflicting for Web UI. 

***Version***
Terraform version: `v1.0.9`
Provider version : `1.2.0`

**To Reproduce**
Create check part of group, have group with different `locations` config than checks. 

**Expected behavior**
When a check is part of the group, `locations` shouldn't be accepted.

**Comment by pshanoop** [comment]
Other configs like `double_check` and `use_global_alert_settings` has no effect if check is part of a group. 

I think it's better to show error in this case, instead of accepting config and making the user think alerts are configured correctly. 

In Web UI, It is not accepting this config if check is part of group.

**Comment by ianaya89** [comment]
@pshanoop thanks for reporting this. We will take a look and evaluate possible solutions

**Comment by ianaya89** [comment]
Resolved #103

**Comment by case** [comment]
I'm seeing something similar, perhaps it's the same issue?

1. I have a `resource = "checkly_check_group"` with a `locations` array specified at the Group level.
2. For the `resource = "checkly_check"` items I'm specifying to be part of this Group, I'm not including a `locations` array, because the docs say it's "Optional." My goal is for each Check to inherit its `locations` config from the Group config, which the Checkly web UI confirms is working.
3. However, with each `terraform plan` I do, I'm seeing this for every `checkly_check` in my codebase:

<img width="434" alt="Screen Shot 2022-03-28 at 15 07 19" src="https://user-images.githubusercontent.com/20105/160495252-7ae520e9-8ad7-44d2-918f-d896045120dc.png">

4. As I add more Checks, I'm seeing this same glitch for each one. It persists after I do a `terraform apply` as well. Here's what the Terraform Cloud web UI is showing as a result of this bug:

<img width="309" alt="Screen Shot 2022-03-28 at 15 10 32" src="https://user-images.githubusercontent.com/20105/160495636-f508aac5-267c-4c1d-924b-5d35be037c22.png">

**Comment by ianaya89** [comment]
This issue was already solved but checks created before this fix could still experience this kind of diff.

- If you can/want re-create the checks, you will not face this issue anymore.
- If you don't want to do that, please reach me at nacho[at]checklyhq.com and I will be happy to help
